<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Menu</name>
   <tag></tag>
   <elementGuidId>841145a3-a45d-469d-af2a-09e53cb1b773</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.back-btn._3y40F1bn > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='app-toolbar']/section/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>29e158d6-6103-467f-ad42-c81dc853fa7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>5f38f9e6-9ab2-47c2-b7fd-5ffe39fae91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-toolbar&quot;)/section[@class=&quot;el-container container-fluid _2tDLkbm6&quot;]/div[@class=&quot;_3nY7Je2-&quot;]/div[@class=&quot;back-btn _3y40F1bn&quot;]/span[1]</value>
      <webElementGuid>55e198d1-235d-447c-9c95-990b054fa440</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='app-toolbar']/section/div/div/span</value>
      <webElementGuid>bc811a33-e097-4f70-91b3-e24436803d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT'])[2]/following::span[2]</value>
      <webElementGuid>b0109030-451b-446e-aee3-2eecc70eaa0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View as'])[1]/following::span[5]</value>
      <webElementGuid>8c6999c7-3d8b-4991-9c8b-c149a6284608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Candidates'])[1]/preceding::span[1]</value>
      <webElementGuid>1fbdf8a2-c1cc-4fdf-86f1-c9653a427677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::span[3]</value>
      <webElementGuid>a2f9fedc-08ea-4186-8f8a-28225a527c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menu']/parent::*</value>
      <webElementGuid>9addbf56-3a2f-4b6a-8316-2babee001e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/section/div/div/span</value>
      <webElementGuid>406a363d-f2c0-4b06-afa1-088550cf3790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Menu' or . = 'Menu')]</value>
      <webElementGuid>ebe45f54-6230-49f2-aef4-42153c1193e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
