<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Users_icon-plus</name>
   <tag></tag>
   <elementGuidId>77a9ea09-dbe2-4de5-aed0-7453e369a493</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_toolbar_icons']/ul/li/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>324e92a7-5383-40b6-8951-571076fc3b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-plus</value>
      <webElementGuid>0a4a885d-9c82-4216-914a-da9f03836460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_toolbar_icons&quot;)/ul[@class=&quot;vertical-toolbar flex-center&quot;]/li[@class=&quot;li-&quot;]/span[@class=&quot;menu cursor-pt v-center&quot;]/i[@class=&quot;icon-plus&quot;]</value>
      <webElementGuid>5e67837c-568d-4e21-a128-33907dcc25c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_toolbar_icons']/ul/li/span/i</value>
      <webElementGuid>721d7a53-d5c0-4030-a97d-566ed2d1f257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>2e20cda6-c08b-4785-b925-74102eaa83e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
