<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Job title_job_title</name>
   <tag></tag>
   <elementGuidId>85120a2a-eeca-418c-8192-6a89e9087d03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_job_title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_job_title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a342fa90-7b2d-4967-85e2-8efb95759ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74243eee-9e41-411a-8ba2-756c96fce11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job_title</value>
      <webElementGuid>b1d46dc1-fd1b-4dca-b431-6507d9d3eff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ai-input None textinput textInput form-control</value>
      <webElementGuid>ddabd0f7-226e-406c-954b-ab28f19059f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_job_title</value>
      <webElementGuid>cfea975c-8552-4dcc-8824-e0eb5e81ef1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>job_title</value>
      <webElementGuid>3d68f487-ffe6-4d86-91c9-a14ff05167ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_job_title&quot;)</value>
      <webElementGuid>6602f098-accb-44a3-aabd-4d8744fc7feb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_job_title']</value>
      <webElementGuid>d15f2054-3c04-43b8-8fe0-99c183f94019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_id_job_title']/div/input</value>
      <webElementGuid>7f1fe9d0-61d8-482b-b513-b3aeb19e29c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>c8454b5b-139e-4df1-9976-b66ad2e8dcf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'job_title' and @id = 'id_job_title']</value>
      <webElementGuid>786f3a1d-d3f7-4dea-93fd-925df1d17fbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
