<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>c8fe5402-9b2e-44f8-9499-5a057b91208c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.el-button.el-button--fullwidth.el-button--primary.el-button--large</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c7e6308-6ee0-402d-9fdd-987094f4df0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c015d24c-98e2-4dc7-be36-5eab77b79249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>login_btn_lookup</value>
      <webElementGuid>e40ba4f3-9390-439f-8306-3718fc6dba65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button el-button--fullwidth el-button--primary el-button--large</value>
      <webElementGuid>25e45aa0-9bb8-44cc-bf52-d35a8539befe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>880cc5af-2774-41bb-88c9-f6adb5b69f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/section[@class=&quot;el-container is-vertical&quot;]/div[@class=&quot;body-wrapper&quot;]/div[@class=&quot;_3Rp4J1Yv&quot;]/div[@class=&quot;el-card el-card__center is-always-shadow _1Hk07WDo&quot;]/div[@class=&quot;el-card__body&quot;]/div[@class=&quot;tPeyOEi1&quot;]/form[@class=&quot;el-form el-form--label-top&quot;]/button[@class=&quot;el-button el-button--fullwidth el-button--primary el-button--large&quot;]</value>
      <webElementGuid>e5bfbe71-9a85-425b-bc14-a2cfc2e5a956</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>076491e4-1f81-429a-9f59-22fafac9c9b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/section/div/div/div/div/div/form/button</value>
      <webElementGuid>5a529e13-61da-4dda-8d19-ef87aad5e1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone number, email, or Employee ID'])[1]/following::button[1]</value>
      <webElementGuid>7d8e4040-e2ea-41c7-b44d-9318419d14ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/following::button[1]</value>
      <webElementGuid>d4a35a5e-ae39-4f8f-ba1c-f1ea34b68a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keep me signed in on this device.'])[1]/preceding::button[1]</value>
      <webElementGuid>6dd4d7e6-4aea-4800-ae1f-eb64bdd4b431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4e7053fa-ee54-43ab-969c-3ad458303cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>41f46228-24e8-4b99-8862-98f565b316d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
