<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone number, email, or Employee ID_l_2fc3e1</name>
   <tag></tag>
   <elementGuidId>243ce38f-02b8-47f5-8383-45e7dfa5f001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='lookup_field']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;lookup_field&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e811b53-f547-4302-ba75-05b5add6cd1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>056d15a2-2690-4f52-907a-fbb41a5de03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ecf8160a-6219-48ef-b273-b717474202da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lookup_field</value>
      <webElementGuid>e26dd84e-9d71-4cd5-9f4f-059ad4dcd2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone number, email, or EID</value>
      <webElementGuid>b7dddd3c-4c91-4143-8742-6140aa8606ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>login_input_lookup</value>
      <webElementGuid>f7618201-59e9-4112-b36b-76527af28cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>74eac6ef-055e-421c-9dc5-51468174f519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/section[@class=&quot;el-container is-vertical&quot;]/div[@class=&quot;body-wrapper&quot;]/div[@class=&quot;_3Rp4J1Yv&quot;]/div[@class=&quot;el-card el-card__center is-always-shadow _1Hk07WDo&quot;]/div[@class=&quot;el-card__body&quot;]/div[@class=&quot;tPeyOEi1&quot;]/form[@class=&quot;el-form el-form--label-top&quot;]/div[@class=&quot;el-form-item&quot;]/div[@class=&quot;el-form-item__content&quot;]/div[@class=&quot;el-input&quot;]/input[@class=&quot;el-input__inner&quot;]</value>
      <webElementGuid>5b34ed6f-6c61-4c3b-96e5-7f7023068289</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='lookup_field']</value>
      <webElementGuid>49b34e50-01dd-45b4-8553-954e3cf17020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/section/div/div/div/div/div/form/div/div/div/input</value>
      <webElementGuid>1d3c706a-153f-413e-90d9-6914be991fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d9fcd47e-d814-4149-ab27-df5496031764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'lookup_field' and @placeholder = 'Phone number, email, or EID']</value>
      <webElementGuid>6e8eef96-c0eb-4532-9567-9334bffe786a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
